### ISSUE TITLE
PHP Fatal error after upgrading from v494 to v501

### ISSUE THREAD

**Issue by kochtopf** [RavanH/xml-sitemap-feed#19]
Hi,
I've got this after upgrading xml-sitemap-feed.

[error] 1754#0: *45212 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: 
Call to undefined function xmlsf_get_archives() in .../wordpress/wp-content/plugins/xml-sitemap-feed/models/admin/main.php:35
#012Stack trace:#012#0 
.../wordpress/wp-includes/class-wp-hook.php(286): xmlsf_nginx_helper_purge_urls(Array, false)
#012#1 .../wordpress/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#012#2 .../wordpress/wp-content/plugins/nginx-helper/purger.php(854): apply_filters('rt_nginx_helper...', Array, false)
#012#3 .../wordpress/wp-content/plugins/nginx-helper/purger.php(140): rtCamp\WP\Nginx\Purger->purge_urls(87741)
#012#4 .../wordpress/wp-content/plugins/nginx-helper/nginx-helper.php(148): rtCamp\WP\Nginx\Purger->purgePost(87741)
#012#5 .../wordpress/wp-includes/class-wp-hook.php(286): rtCamp\WP\Nginx\Helper->set_future_post_option_on_future_status('trash', 'publish', Object(WP_Post))
#012#6 .../wordpress/wp-includes/class-wp-hook" while reading response header from upstream, client: 192.168.0.102,
, request: "GET /wp-admin/post.php?post=87741&action=trash&_wpnonce=eb60193fbf HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:",
---
The part of the nginx-helper (plugin) that calls the filter is:
// Allow plugins/themes to modify/extend urls. Pass urls array in first parameter, second says if wildcards are allowed
$purge_urls = apply_filters('rt_nginx_helper_purge_urls', $purge_urls, false);
---
A quick fix for this problem is:
diff main_ORI.php main.php      ;fix for >v5.0.1
12a13
> require_once XMLSF_DIR . '/models/public/sitemap.php';
---
Please could you review this change for a future release. It may be not at the right place. At least - it's working for me. Thanks for reading.

**Comment by RavanH** [comment]
Hi @kochtopf thanks for reporting! It does indeed need the models/public/sitemap.php included there. Your fix will be added to the next release :)
