### ISSUE TITLE
Not compatible with other sitemap plugin

### ISSUE THREAD

**Issue by Satheeshraj1** [RavanH/xml-sitemap-feed#25]
I have installed Google XML sitemap plugin in my site. After that for indexing news alone I have installed Google news sitemap plugin. But sitemap-news.xml doesn't contain any url. When I uninstall the Google sitemap plugin the news sitemap plugin started working.

Note : This issue is occurring in WordPress plugin

**Comment by RavanH** [comment]
Hi @Satheeshraj1 could you install the latest development release from https://github.com/RavanH/xml-sitemap-feed/archive/master.zip (download, unzip and upload by FTP overwriting the files in wp-content/plugins/xml-sitemap-feed/) then reactivate the other sitemap plugin and let me know if the problem persists :)
