### ISSUE TITLE
not updating the tags site map.

### ISSUE THREAD

**Issue by khurram55pk** [RavanH/xml-sitemap-feed#26]
I have 600k tags in my website but the sitemap is only 50k supported. how I can fix. and the other issue is how i can create the amp site map

**Comment by RavanH** [comment]
More than 50k tags is not supported at this moment. I'm not sure it ever will, seen as taxonomy archive pages are generally not recommended to feature in a sitemap anyway... The plugin takes care to include the most used tags.

A dedicated amp sitemap is not available but it's something to consider. Which plugin are you using for AMP pages? I suppose it creates `<link rel="amphtml" href=".../amp/">` tags in the normal page head so search engines will find them just fine, no? If so, they WILL be found and indexed, I'm sure.
