### ISSUE TITLE
Undefined index: xmlsf_priority in xml-sitemap-feed/controllers/admin/main.php on line 321

### ISSUE THREAD

**Issue by gerdneuman** [RavanH/xml-sitemap-feed#27]
When testing things (totally unrelated to the xml sitemap plugin) I usually have WP_DEBUG enabled on my staging system to see errors in the logs. This thing come along and I thought of letting you know:

```
PHP Notice:  Undefined index: xmlsf_priority in /var/www/staging.2018-12-10-00-13-30/www.mysite.org/htdocs/wp-content/plugins/xml-sitemap-feed/controllers/admin/main.php on line 321
PHP Stack trace:
PHP   1. {main}() /var/www/staging.2018-12-10-00-13-30/www.mysite.org/htdocs/wp-admin/post.php:0
PHP   2. post_preview() /var/www/staging.2018-12-10-00-13-30/www.mysite.org/htdocs/wp-admin/post.php:279
PHP   3. wp_create_post_autosave() /var/www/staging.2018-12-10-00-13-30/www.mysite.org/htdocs/wp-admin/includes/post.php:1783
PHP   4. wp_update_post() /var/www/staging.2018-12-10-00-13-30/www.mysite.org/htdocs/wp-admin/includes/post.php:1743
PHP   5. wp_insert_post() /var/www/staging.2018-12-10-00-13-30/www.mysite.org/htdocs/wp-includes/post.php:3746
PHP   6. do_action() /var/www/staging.2018-12-10-00-13-30/www.mysite.org/htdocs/wp-includes/post.php:3673
PHP   7. WP_Hook->do_action() /var/www/staging.2018-12-10-00-13-30/www.mysite.org/htdocs/wp-includes/plugin.php:453
PHP   8. WP_Hook->apply_filters() /var/www/staging.2018-12-10-00-13-30/www.mysite.org/htdocs/wp-includes/class-wp-hook.php:310
PHP   9. XMLSF_Admin_Controller->save_metadata() /var/www/staging.2018-12-10-00-13-30/www.mysite.org/htdocs/wp-includes/class-wp-hook.php:288
```

Sorry, I cannot give any further hint. I might have edited my frontpage (which is a normal page acting as wordpress frontpage), but really not sure. I just noticed the stacktrace in the logs some hours later. And maybe a check can be introduced in the code to avoid the `Undefined Notice`.

If this is not actionable, then please just close the issue. I am not a PHP developer so I do not know how helpful or sufficient a stack trace alone can be.

And: A late Happy new Year!  :)

**Comment by RavanH** [comment]
Hi Gerd, happy new year to you too and thank you for the report. I've identified the issue and it will be fixed in the upcoming release :)
