### ISSUE TITLE
Hi, help me.

### ISSUE THREAD

**Issue by tongjookim** [RavanH/xml-sitemap-feed#37]
I always thank the developer and use the plug-in.

In the process of setting up contents at the latest Google Publishers Center,
The xml address of this plug-in cannot retrieve content.
I want to know the cause, but I am not a professional developer, so I don't

Please help this person.

Thank you.

Kim Tongjoo in South Korea.

**Comment by RavanH** [comment]
Hi, for debugging help please see the support forum https://wordpress.org/support/plugin/xml-sitemap-feed/
