### ISSUE TITLE
Bug when plugin clears Nginx Helper post sitemap cache

### ISSUE THREAD

**Issue by janvitos** [RavanH/xml-sitemap-feed#38]
Hi,

Thanks for this awesome plugin.

I noticed today that there is a bug when Nginx Helper tries to clear the cache for the post sitemaps.

This is what I get in the Nginx Helper log for the various post sitemaps:

```
Purging URL | https://www.website.com44:17-04:00
Purging URL | https://www.website.com07:10-04:00
Purging URL | https://www.website.com50:25-04:00
```

The URLs should look like this:

```
Purging URL | https://www.website.com/sitemap-posttype-post.2022.xml
Purging URL | https://www.website.com/sitemap-posttype-post.2021.xml
Purging URL | https://www.website.com/sitemap-posttype-post.2020.xml
```

It seems the issue is most probably related to the xmlsf_get_index_archive_data function.

I can assist if you need help debugging / testing.

Thank you.

**Comment by RavanH** [comment]
Hi janvitos, yes the bug is known but has not been addressed yet. You closed this why?
