### ISSUE TITLE
Run this programaticly

### ISSUE THREAD

**Issue by rhildred** [RavanH/xml-sitemap-feed#55]
Thanks for a great tool. I have built a wordpress "bundler" and I need a way to get all of routes/pages from a wordpress site. Node php looks specifically for .php in a file. I had to hack it to generate a sitemap . Can you think of a way that I could run your plugin directly to make a sitemap that includes all of the routes in the site?

**Comment by RavanH** [comment]
Hi, the sitemaps are dynamically created, just like feeds, pages or posts. Does your bundler detect feeds?

**Comment by rhildred** [comment]
My bundler selects from wp-posts where wp-status = published and post-type = page or post-type =post.

I was hoping to get all of the routes like you do for the sitemap. I am looking at the code, but thought I would ask too, if you could think of a way that I could use your code to return an array of all of the routes on the wordpress site with php or sql.

**Comment by RavanH** [comment]
directly from the database? no sorry, the plugin only stores some post meta data in the database but that seems useless for your bundler... you could consider the feed template files under /views/feed-sitemap*.php as "endpoints" which might inspire you?

**Comment by rhildred** [comment]
Hi Again:

I got this to work from my bundler by using `run` instead of `request` from node-php.

Thanks so much for your responsiveness and the plugin.
